# Generated by Django 3.2.5 on 2021-07-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
